### ISSUE TITLE
Removing remote event receivers from the lists and webs just by clicking delete option

### ISSUE THREAD

**Issue by ParthasarathyBalan** [bramdejager/spcb#78]
It would be more helpful if we can delete custom remote receivers which is attached to the SharePoint lists and webs.we are facing the problems like attaching wrong url's to the lists and webs of SharePoint sites.we can't remove it using CSOM code as well it is showing Access denied error,we can delete the event receivers attached to the Lists using SharePoint designer for SharePoint online likewise it will be better to get an option like this in spcb.

**Comment by bramdejager** [comment]
Hi, the SPCB tool is a read-only tool. It has always been this way and will stay this way. Its purpose is to get insights into the SharePoint structure/hierarchy, properties and related values. The tool is not for changing values in any way. You can use the [PnP PowerShell cmdlets](https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-pnp/sharepoint-pnp-cmdlets?view=sharepoint-ps) for this purpose without having to do coding, otherwise you can use the CSOM off course.
