### ISSUE TITLE
TLS 1.2 Required in O365. SPCB supports this?

### ISSUE THREAD

**Issue by scervenak** [bramdejager/spcb#86]
When attempting to connect to an O365 Site collection, I'm getting "The request was aborted: Could not create SSL/TLS secure channel." 

Since O365 just switched off support for TLS 1.0 and 1.1 as of a couple of weeks ago (Oct 31 2018), I presume SPCB needs a small update to use the correct security?

**Comment by bramdejager** [comment]
The support for TLS 1.1 and TLS 1.2 is included in SPCB tool since early this calendar year. Just validated by connecting to a SPO site and it is still working for me. Let know if you still face the issue? If so, can you provide the log files ?

Please follow instructions on the [Report a Bug](https://github.com/bramdejager/spcb/blob/master/docs/ReportBug.md) page.

**Comment by scervenak** [comment]
Attached is the Verbose log file.
[SPCB-BS-SEC-20181113.log](https://github.com/bramdejager/spcb/files/2577026/SPCB-BS-SEC-20181113.log)

**Comment by bramdejager** [comment]
Thanks for providing the log file. I see you are using version 3.3.0.0, which is not the latest version. Can you download the latest version? 

Check out the right version on the homepage, see [Releases & Downloads](https://github.com/bramdejager/spcb#releases--downloads).

Let me know if that fixed your problem.

**Comment by scervenak** [comment]
The latest version fixed it. 
I thought I was on the latest version, since using the "Check for updates" in the app reported that there was no newer release. I should have manually checked. 
Thanks for your prompt resolution.
